# Generated by Django 3.0.7 on 2020-09-01 22:42

import core.utils.utils_models
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="images/default_profile.png",
                storage=core.utils.utils_models.OverwriteStorage(),
                upload_to=users.models.user_namespace_path,
            ),
        ),
    ]
