# Generated by Django 3.0.7 on 2020-09-08 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("countrycuzzins", "0017_auto_20200907_0535"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_auto_20200901_1842"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("like", models.IntegerField(default=0)),
                ("heart", models.IntegerField(default=0)),
                ("dislike", models.IntegerField(default=0)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Likes",
            fields=[
                (
                    "rating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.Rating",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="user_ratings", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video",
                        to="countrycuzzins.Video",
                    ),
                ),
            ],
        ),
    ]
