# Generated by Django 3.0.7 on 2020-08-27 10:35

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200826_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/default_profile.png', upload_to=users.models.user_namespace_path),
        ),
    ]
