# Generated by Django 3.0.7 on 2020-09-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20200908_0341"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=60, null=True)),
                ("lastname", models.CharField(max_length=60, null=True)),
                ("email", models.CharField(max_length=100, null=True)),
                ("message", models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
