# Generated by Django 3.0.7 on 2020-09-21 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_contactus"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactus",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
