# Generated by Django 3.0.7 on 2020-09-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200922_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='ip_address',
            field=models.CharField(blank=True, default=1, max_length=30),
            preserve_default=False,
        ),
    ]
