# Generated by Django 3.0.7 on 2020-09-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200923_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
