# Generated by Django 3.0.7 on 2020-09-23 22:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_newletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newLetter',
            new_name='NewsLetter',
        ),
    ]
