# Generated by Django 3.0.7 on 2020-10-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("countrycuzzins", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="is_music",
        ),
        migrations.AlterField(
            model_name="video",
            name="rating",
            field=models.ManyToManyField(
                blank=True, related_name="video_ratings", to="core.Rating"
            ),
        ),
    ]
