# Generated by Django 3.0.7 on 2020-09-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(help_text='<p style="color:#000; font-weight:700;"> Select ALL songs that will be on album</p>', related_name='album_songs', to='countrycuzzins.Album', verbose_name='Album name'),
        ),
    ]
