# Generated by Django 3.0.7 on 2020-08-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_music',
            field=models.BooleanField(default=True),
        ),
    ]
