# Generated by Django 3.0.7 on 2020-07-07 02:03

import countrycuzzins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0002_auto_20200705_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=countrycuzzins.models.toNameSpace),
        ),
    ]
