# Generated by Django 3.0.7 on 2020-08-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0002_auto_20200821_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_youtube',
            field=models.BooleanField(default=False),
        ),
    ]
