# Generated by Django 3.0.7 on 2020-10-01 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("countrycuzzins", "0002_auto_20201001_0009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="producer",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="video_producer",
                to="countrycuzzins.Producer",
                verbose_name="video producer",
            ),
        ),
    ]
