# Generated by Django 3.0.7 on 2020-07-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0003_auto_20200707_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_showcase',
            field=models.BooleanField(default=False),
        ),
    ]
