# Generated by Django 3.0.7 on 2020-10-01 06:37

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0004_auto_20201001_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2020, 10, 1, 6, 37, 36, 492949, tzinfo=utc), help_text='<span id="myslughelp"></span>', max_length=80, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='video url'),
            preserve_default=False,
        ),
    ]
