# Generated by Django 3.0.7 on 2020-12-15 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0006_auto_20201002_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='', editable=False, help_text='<p style="color:red; font-weight:700;"> DO NOT ADD DASHES</p>', max_length=80, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='album url'),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(default='', help_text='<p style="color:red; font-weight:700;"> DO NOT ADD DASHES</p>', max_length=80, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
