# Generated by Django 3.0.7 on 2020-12-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0007_auto_20201215_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Do you want this on the home page'),
        ),
    ]
