# Generated by Django 3.0.7 on 2020-07-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0007_auto_20200707_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='cropping',
        ),
    ]
