# Generated by Django 3.0.7 on 2020-12-16 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0008_album_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='played_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=150, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=150, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
