# Generated by Django 3.0.7 on 2020-09-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countrycuzzins", "0008_auto_20200826_0820"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="Event name",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("event_date", models.DateField()),
            ],
        ),
    ]
