# Generated by Django 3.0.7 on 2020-07-08 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0008_remove_image_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=60, unique=True),
        ),
        migrations.CreateModel(
            name='ShowCaseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=60, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_image', to='countrycuzzins.Image')),
            ],
        ),
    ]
