# Generated by Django 3.0.7 on 2020-07-08 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0009_auto_20200708_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcaseimage',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='showcaseimage',
            name='id',
        ),
        migrations.AlterField(
            model_name='showcaseimage',
            name='image',
            field=models.OneToOneField(default='media/images/no_image.png', on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='countrycuzzins.Image'),
        ),
    ]
