# Generated by Django 3.0.7 on 2020-12-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0009_auto_20201216_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(related_name='album', to='countrycuzzins.Song'),
        ),
    ]
