# Generated by Django 3.0.7 on 2020-09-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countrycuzzins", "0010_auto_20200901_1847"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event", name="event_date", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Example: Jackson MS colosseum or Facebook live",
                max_length=100,
                null=True,
            ),
        ),
    ]
