# Generated by Django 3.0.7 on 2020-12-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0010_auto_20201216_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file',
            new_name='audio',
        ),
    ]
