# Generated by Django 3.0.7 on 2020-07-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0010_auto_20200708_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaseimage',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
