# Generated by Django 3.0.7 on 2020-12-17 00:43

import core.utils.utils_models
import countrycuzzins.music_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0011_auto_20201216_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(max_length=120, storage=core.utils.utils_models.OverwriteStorage(), upload_to=countrycuzzins.music_models.makeSongName),
        ),
    ]
