# Generated by Django 3.0.7 on 2020-07-08 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0012_image_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('image', models.OneToOneField(default='media/images/no_image.png', on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='countrycuzzins.Image')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='ShowCaseImage',
        ),
    ]
