# Generated by Django 3.0.7 on 2020-12-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0012_auto_20201216_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(default=1, to='countrycuzzins.Artist'),
        ),
    ]
