# Generated by Django 3.0.7 on 2020-09-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countrycuzzins", "0012_auto_20200901_1907"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="long_description",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
