# Generated by Django 3.0.7 on 2020-07-08 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0013_auto_20200708_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='Url for this article (basically just a name)</br><br/>\n                       <div style="color:#000;font-size:14px;">\n                        ( <span style="color:green;font-weight:700;">\n                          Example</span>:&nbsp;\'Now or Never picture\' )</div>\n                     ', max_length=80, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
