# Generated by Django 3.0.7 on 2020-09-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countrycuzzins", "0013_video_long_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="long_description",
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
