# Generated by Django 3.0.7 on 2020-12-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0013_auto_20201216_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_main_artist',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(related_name='songs', to='countrycuzzins.Song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(blank=True, null=True, related_name='main_artist', to='countrycuzzins.Artist'),
        ),
    ]
