# Generated by Django 3.0.7 on 2020-12-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0014_auto_20201217_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='feature',
            new_name='feature_artist',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='is_main_artist',
        ),
    ]
