# Generated by Django 3.0.7 on 2020-09-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countrycuzzins", "0014_auto_20200907_0338"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=80, unique=True)),
                ("company", models.CharField(blank=True, max_length=120, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "video_produced",
                    models.ManyToManyField(
                        null=True,
                        to="countrycuzzins.Video",
                        verbose_name="video produced",
                    ),
                ),
            ],
        ),
    ]
