# Generated by Django 3.0.7 on 2020-07-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0014_auto_20200708_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='headline',
        ),
    ]
