# Generated by Django 3.0.7 on 2020-07-09 00:57

import countrycuzzins.models
from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0015_auto_20200708_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '420x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=image_cropping.fields.ImageCropField(upload_to=countrycuzzins.models.toNameSpace),
        ),
    ]
