# Generated by Django 3.0.7 on 2020-12-17 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0015_auto_20201217_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='article',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(default='Country Cuzzins Artist', max_length=500),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='countrycuzzins.Image'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='feature_artist',
        ),
        migrations.AddField(
            model_name='song',
            name='feature_artist',
            field=models.ManyToManyField(blank=True, help_text='<p style="color:#000; font-weight:700;"> Feature Artist(s) Only </p><span>(optional)</span>', null=True, related_name='featured_artist', to='countrycuzzins.Artist', verbose_name='feature artists(s)'),
        ),
    ]
