# Generated by Django 3.0.7 on 2020-09-07 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("countrycuzzins", "0015_producer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="company",
            field=models.CharField(blank=True, default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.RemoveField(model_name="producer", name="video_produced",),
        migrations.AddField(
            model_name="producer",
            name="video_produced",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="countrycuzzins.Video",
                verbose_name="video produced",
            ),
            preserve_default=False,
        ),
    ]
