# Generated by Django 3.0.7 on 2020-07-09 01:28

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0016_auto_20200708_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '1024x768', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=image_cropping.fields.ImageCropField(upload_to='images'),
        ),
    ]
