# Generated by Django 3.0.7 on 2020-09-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("countrycuzzins", "0016_auto_20200907_0516"),
    ]

    operations = [
        migrations.RemoveField(model_name="producer", name="video_produced",),
        migrations.AddField(
            model_name="video",
            name="producer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="countrycuzzins.Producer",
                verbose_name="video producer",
            ),
            preserve_default=False,
        ),
    ]
