# Generated by Django 3.0.7 on 2020-09-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countrycuzzins", "0017_auto_20200907_0535"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thumbnail_choice",
            field=models.IntegerField(
                choices=[(1, 0), (2, 1), (3, 2), (4, 3)],
                default=1,
                verbose_name="thumbnail",
            ),
        ),
    ]
