# Generated by Django 3.0.7 on 2020-12-18 22:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0017_auto_20201217_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_producer', to='countrycuzzins.Producer', verbose_name='video producer'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(editable=False, max_length=120, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='video slug'),
        ),
    ]
