# Generated by Django 3.0.7 on 2020-09-08 08:43

import NoworNever.utils.utils_models
import countrycuzzins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countrycuzzins", "0018_video_thumbnail_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                storage=NoworNever.utils.utils_models.OverwriteStorage(),
                upload_to=countrycuzzins.models.toNameSpace,
            ),
        ),
    ]
