# Generated by Django 3.0.7 on 2020-12-18 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0018_auto_20201218_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(editable=False, max_length=120, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='video slug'),
        ),
    ]
