# Generated by Django 3.0.7 on 2020-07-09 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0019_auto_20200708_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='cropping',
        ),
    ]
