# Generated by Django 3.0.7 on 2020-12-19 00:16

import core.utils.utils_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0020_auto_20201218_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, storage=core.utils.utils_models.OverwriteStorage(), upload_to='images'),
        ),
    ]
