# Generated by Django 3.0.7 on 2020-12-19 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0021_auto_20201218_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
    ]
