# Generated by Django 3.0.7 on 2020-07-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0021_auto_20200708_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
