# Generated by Django 3.0.7 on 2020-07-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0022_auto_20200708_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
