# Generated by Django 3.0.7 on 2020-07-09 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0024_auto_20200708_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='updated_date',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='upload_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='updated_date',
            new_name='updated',
        ),
    ]
