# Generated by Django 3.0.7 on 2020-12-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0024_auto_20201218_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
