# Generated by Django 3.0.7 on 2020-09-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countrycuzzins", "0024_remove_video_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thumbnail",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
