# Generated by Django 3.0.7 on 2020-12-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0025_album_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, help_text='<div class="text-danger"> html safe</div>', max_length=1000, null=True),
        ),
    ]
