# Generated by Django 3.0.7 on 2020-07-17 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0026_auto_20200716_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='name',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(default='audio/1', help_text='<p style="color:red; font-weight:700;"> DO NOT ADD DASHES</p>', max_length=80, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
