# Generated by Django 3.0.7 on 2020-07-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0027_auto_20200716_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='feature',
            field=models.CharField(blank=True, default='', help_text='<p style="color:#000; font-weight:700;"> Feature Artist(s) Only </p>(optional)', max_length=120, null=True, verbose_name='feature artists(s)'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, default='Country Cuzzins', help_text='<p style="color:#000; font-weight:700;"> Main Artist(s) Only</p>', max_length=120, null=True, verbose_name='artist(s)'),
        ),
    ]
