# Generated by Django 3.0.7 on 2020-07-17 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0028_auto_20200716_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='feature',
            field=models.CharField(blank=True, default='', help_text='<p style="color:#000; font-weight:700;"> Feature Artist(s) Only </p><span>(optional)</span>', max_length=120, null=True, verbose_name='feature artists(s)'),
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('article', models.ManyToManyField(blank=True, default=False, to='countrycuzzins.Article', verbose_name='article(s)')),
                ('profile_image', models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='countrycuzzins.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_image', to='countrycuzzins.Image')),
                ('songs', models.ManyToManyField(blank=True, help_text='<p style="color:#000; font-weight:700;"> Select ALL songs that will be on album</p>', to='countrycuzzins.Song', verbose_name='list of songs')),
            ],
        ),
    ]
