# Generated by Django 3.0.7 on 2020-07-17 10:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0029_auto_20200717_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.OneToOneField(default='images/no_content.png', on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='countrycuzzins.Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='Url for this article (basically just a name)</br><br/>\n                       <div style="color:#000;font-size:14px;">\n                        ( <span style="color:green;font-weight:700;">\n                          Example</span>:&nbsp;\'Now or Never picture\' )</div>\n                     ', max_length=80, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='article name'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='article',
            field=models.ManyToManyField(blank=True, default=1, to='countrycuzzins.Article', verbose_name='article(s)'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_image',
            field=models.OneToOneField(default='images/no_image_artist.png', on_delete=django.db.models.deletion.SET_DEFAULT, to='countrycuzzins.Image'),
        ),
        migrations.AlterField(
            model_name='song',
            name='feature',
            field=models.CharField(blank=True, help_text='<p style="color:#000; font-weight:700;"> Feature Artist(s) Only </p><span>(optional)</span>', max_length=120, null=True, verbose_name='feature artists(s)'),
        ),
    ]
