# Generated by Django 3.0.7 on 2020-07-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0030_auto_20200717_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='article',
            field=models.ManyToManyField(blank=True, null=True, to='countrycuzzins.Article', verbose_name='article(s)'),
        ),
    ]
