# Generated by Django 3.0.7 on 2020-07-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0031_auto_20200717_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='slug',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
    ]
