# Generated by Django 3.0.7 on 2020-07-17 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0032_auto_20200717_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='article/1', help_text='\n    Url for this article (basically just a name)</br><br/>\n    <div style="color:#000;font-size:14px;">\n    ( <span style="color:green;font-weight:700;">\n      Example</span>:&nbsp;\'Now or Never picture\' )</div>\n  ', max_length=80, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='article url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(blank=True, max_length=60, unique=True),
        ),
    ]
