# Generated by Django 3.0.7 on 2020-07-17 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0033_auto_20200717_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='\n    Url for this article (basically just a name)</br><br/>\n    <div style="color:#000;font-size:14px;">\n    ( <span style="color:green;font-weight:700;">\n      Example</span>:&nbsp;\'Now or Never picture\' )</div>\n  ', max_length=80, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='article url'),
        ),
    ]
