# Generated by Django 3.0.7 on 2020-07-17 11:04

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0035_remove_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, help_text='\n    Url for this article (basically just a name)</br><br/>\n    <div style="color:#000;font-size:14px;">\n    ( <span style="color:green;font-weight:700;">\n      Example</span>:&nbsp;\'Now or Never picture\' )</div>\n  ', max_length=80, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='article url'),
            preserve_default=False,
        ),
    ]
