# Generated by Django 3.0.7 on 2020-07-23 05:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0036_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='blog',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.OneToOneField(blank=True, default='images/no_content.png', on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='countrycuzzins.Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='<span id="myslughelp"></span>', max_length=80, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='article url'),
        ),
    ]
