# Generated by Django 3.0.7 on 2020-07-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0045_auto_20200723_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='article',
            field=models.ManyToManyField(to='countrycuzzins.Article', verbose_name='article(s)'),
        ),
    ]
