# Generated by Django 3.0.7 on 2020-07-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0047_remove_album_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
