# Generated by Django 3.0.7 on 2020-07-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0048_album_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='album',
            name='songs',
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(help_text='<p style="color:#000; font-weight:700;"> Select ALL songs that will be on album</p>', to='countrycuzzins.Song', verbose_name='list of songs'),
        ),
    ]
