# Generated by Django 3.0.7 on 2020-07-23 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0050_auto_20200723_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
    ]
