# Generated by Django 3.0.7 on 2020-07-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0055_auto_20200723_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=120, primary_key=True, serialize=False, unique=True),
        ),
    ]
