# Generated by Django 3.0.7 on 2020-07-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0057_auto_20200723_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
    ]
