# Generated by Django 3.0.7 on 2020-07-23 08:18

import countrycuzzins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0058_auto_20200723_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(upload_to=countrycuzzins.models.toNameSpace),
        ),
    ]
