# Generated by Django 3.0.7 on 2020-07-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0059_auto_20200723_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song',
            new_name='name',
        ),
    ]
