# Generated by Django 3.0.7 on 2020-07-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0061_auto_20200723_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image',
        ),
    ]
