# Generated by Django 3.0.7 on 2020-07-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0065_auto_20200723_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image',
        ),
        migrations.RemoveField(
            model_name='album',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='album',
            name='songs',
        ),
    ]
