# Generated by Django 3.0.7 on 2020-07-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0067_auto_20200723_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='name2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
