# Generated by Django 3.0.7 on 2020-07-23 12:04

import countrycuzzins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0068_album_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='song',
            name='name',
        ),
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default=1, upload_to=countrycuzzins.models.toNameSpace, verbose_name='song file'),
            preserve_default=False,
        ),
    ]
