# Generated by Django 3.0.7 on 2020-07-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0069_auto_20200723_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=120, null=True, unique=True, verbose_name='title'),
        ),
    ]
