# Generated by Django 3.0.7 on 2020-07-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0070_auto_20200723_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file',
            new_name='le',
        ),
    ]
