# Generated by Django 3.0.7 on 2020-07-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0072_auto_20200723_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
