# Generated by Django 3.0.7 on 2020-07-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0073_auto_20200723_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.CharField(default='1', max_length=60),
            preserve_default=False,
        ),
    ]
