# Generated by Django 3.0.7 on 2020-07-23 12:24

import countrycuzzins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0074_auto_20200723_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(default='1', upload_to=countrycuzzins.models.toNameSpace, verbose_name='song file'),
        ),
    ]
