# Generated by Django 3.0.7 on 2020-07-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0075_auto_20200723_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.CharField(max_length=60),
        ),
    ]
