# Generated by Django 3.0.7 on 2020-07-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0078_auto_20200723_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='le',
        ),
    ]
