# Generated by Django 3.0.7 on 2020-07-23 12:31

import countrycuzzins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0080_song_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to=countrycuzzins.models.toNameSpace, verbose_name='song file'),
        ),
    ]
