# Generated by Django 3.0.7 on 2020-07-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0083_song_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='', verbose_name='song file'),
        ),
    ]
