# Generated by Django 3.0.7 on 2020-07-23 13:05

import countrycuzzins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0084_auto_20200723_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to=countrycuzzins.models.toNameSpace, verbose_name='song file'),
        ),
    ]
