# Generated by Django 3.0.7 on 2020-08-02 03:58

import countrycuzzins.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countrycuzzins', '0085_auto_20200723_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ForeignKey(default='images/_no_image_profile.png', on_delete=django.db.models.deletion.DO_NOTHING, related_name='album_image', to='countrycuzzins.Image'),
        ),
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(help_text='<p style="color:#000; font-weight:700;"> Select ALL songs that will be on album</p>', related_name='album_songs', to='countrycuzzins.Song', verbose_name='list of songs'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, storage=countrycuzzins.models.OverwriteStorage(), upload_to=countrycuzzins.models.toNameSpace),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(max_length=120, storage=countrycuzzins.models.OverwriteStorage(), upload_to=countrycuzzins.models.makeSongName, verbose_name='song file'),
        ),
    ]
