# Generated by Django 3.2 on 2021-04-17 06:32

import core.utils.utils_models
import countrycuzzins.music_models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('bio', models.TextField(default='Country Cuzzins Artist', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Event name')),
                ('location', models.CharField(help_text='Example: Jackson MS colosseum or Facebook live', max_length=100)),
                ('event_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('image', models.ImageField(upload_to='images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('link', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='social media site name')),
                ('link', models.CharField(max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('url', models.URLField(max_length=300, null=True)),
                ('thumbnail_choice', models.IntegerField(choices=[(0, 1), (1, 2), (2, 3), (3, 4)], default=1, verbose_name='choose a thumbnail')),
                ('thumbnail', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description', models.CharField(blank=True, max_length=100, null=True)),
                ('long_description', models.TextField(blank=True, max_length=600, null=True)),
                ('slug', models.SlugField(editable=False, max_length=120, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='video slug')),
                ('is_featured', models.BooleanField(default=False, help_text='special video that will be highlighted and featured on website')),
                ('is_youtube', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_producer', to='countrycuzzins.producer', verbose_name='video producer')),
                ('rating', models.ManyToManyField(blank=True, related_name='video_ratings', to='core.Rating')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True, unique=True, verbose_name='title')),
                ('audio', models.FileField(max_length=120, storage=core.utils.utils_models.OverwriteStorage(), upload_to=countrycuzzins.music_models.makeSongName)),
                ('played_count', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default='', editable=False, max_length=150, validators=[django.core.validators.MinLengthValidator(4)])),
                ('artist', models.ManyToManyField(related_name='main_artist', to='countrycuzzins.Artist')),
                ('feature_artist', models.ManyToManyField(blank=True, help_text='<p style="color:#000; font-weight:700;"> Feature Artist(s) Only </p><span>(optional)</span>', related_name='featured_artist', to='countrycuzzins.Artist', verbose_name='feature artists(s)')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='countrycuzzins.image'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='<div style="color:red"> HTML SAFE</div>', max_length=1000, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Do you want this on the home page')),
                ('slug', models.SlugField(default='', editable=False, max_length=150, validators=[django.core.validators.MinLengthValidator(4)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cover', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='album_cover', to='countrycuzzins.image')),
                ('songs', models.ManyToManyField(related_name='songs', to='countrycuzzins.Song')),
            ],
        ),
    ]
