# Generated by Django 3.1.8 on 2021-04-17 08:25

import countrycuzzins.music_models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_contactus_ip_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countrycuzzins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='created',
        ),
        migrations.RemoveField(
            model_name='album',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='created',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='image',
            name='created',
        ),
        migrations.RemoveField(
            model_name='image',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='created',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='video',
            name='created',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_choice',
        ),
        migrations.RemoveField(
            model_name='video',
            name='updated',
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='countrycuzzins.image'),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Set True to put some on home page'),
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='countrycuzzins.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(max_length=120, upload_to=countrycuzzins.music_models.makeSongName),
        ),
        migrations.AlterField(
            model_name='song',
            name='feature_artist',
            field=models.ManyToManyField(blank=True, help_text='<p style="color:#000; font-weight:700;"> Feature Artist(s) Only </p><span>(optional)</span>', related_name='feature_artist', to='countrycuzzins.Artist', verbose_name='feature artists(s)'),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='video',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='countrycuzzins.producer', verbose_name='video producer'),
        ),
        migrations.AlterField(
            model_name='video',
            name='rating',
            field=models.ManyToManyField(blank=True, to='core.Rating'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(editable=False, max_length=120, verbose_name='video slug'),
        ),
        migrations.CreateModel(
            name='HistoricalVideo',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('url', models.URLField(max_length=300, null=True)),
                ('short_description', models.CharField(blank=True, max_length=100, null=True)),
                ('long_description', models.TextField(blank=True, max_length=600, null=True)),
                ('slug', models.SlugField(editable=False, max_length=120, verbose_name='video slug')),
                ('is_featured', models.BooleanField(default=False, help_text='special video that will be highlighted and featured on website')),
                ('is_youtube', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('producer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='countrycuzzins.producer', verbose_name='video producer')),
            ],
            options={
                'verbose_name': 'historical video',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSong',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, null=True, verbose_name='title')),
                ('audio', models.TextField(max_length=120)),
                ('played_count', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('slug', models.SlugField(editable=False, max_length=150)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical song',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSocialMedia',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='social media site name')),
                ('link', models.CharField(max_length=250, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical social media',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProducer',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('link', models.URLField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical producer',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalImage',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60)),
                ('image', models.TextField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical image',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Event name')),
                ('location', models.CharField(help_text='Example: Jackson MS colosseum or Facebook live', max_length=100)),
                ('event_date', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical event',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalArtist',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('bio', models.TextField(default='Country Cuzzins Artist', max_length=500)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='countrycuzzins.image')),
            ],
            options={
                'verbose_name': 'historical artist',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAlbum',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, help_text='<div style="color:red"> HTML SAFE</div>', max_length=1000, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Set True to put some on home page')),
                ('slug', models.SlugField(editable=False, max_length=150, validators=[django.core.validators.MinLengthValidator(4)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cover', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='countrycuzzins.image')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical album',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
